[build]
publish = "_site"
command = "npm run build"

[[redirects]]
from = "/guides/guide-draft/"
to = "/.netlify/functions/dynamic"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamic"

[[redirects]]
from = "/"
to = "/.netlify/functions/dynamic"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamic"

[[redirects]]
from = "/"
to = "/"
status = 302
force = true

  [redirects.conditions]
  Cookie = [ "_11ty_oauth_token" ]
